name: delete branch on close pr
on: 
  pull_request:
    types: [closed]
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with: 
          exclude: 
            - develop
            - master
            - release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}